version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: app-docker_laravel
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - network

    database:
        image: postgres:latest
        container_name: db-docker_laravel
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            TZ: America/Sao_Paulo
            POSTGRES_DB: game
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        volumes:
            - ./database/data:/var/lib/postgres
        networks:
            - network

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - network

networks:
    network:
        driver: bridge
